networks:
  stock-market-network:
    external: true

services:
  dbt-base:
    build:
      context: .
      dockerfile: dbt.dockerfile
      network: host
    image: dbt-stock-market
    volumes:
      - ./stock_market_data:/usr/app/dbt/
      - ./stock_market_data/profiles.yml:/root/.dbt/profiles.yml
    networks:
      - stock-market-network
