stock_market_data:
  outputs:
    dev:
      dbname: stock_market
      host: stock-market-postgres
      pass: postgres
      port: 5432
      schema: public
      threads: 4
      type: postgres
      user: postgres
  target: dev
